// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnjkuwuvonfnyohdmvjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uamt1d3V2b25mbnlvaGRtdmpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNjcyNTQsImV4cCI6MjA2MTY0MzI1NH0.BLYrrTQSrZgM5PA91jmeqDBn59ZXYxGjD-38EL7dPAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);